aws_region = "eu-central-1"
db_instance_identifier = "rds-dev-tf"
master_username = "devadmin"
master_password = "your_secure_password"
db_instance_class = "db.m6i.xlarge"
allocated_storage = 260
storage_type = "gp3"
engine_version = "11.5.9.0.sb00046591.r1"
db_subnet_group_name = "rds_subnet_group_dev"
vpc_security_group_ids = ["sg-xxxxxxxx"]
db_parameter_group_name = "standarddb2-dev-tf"
database_port = 50000
backup_retention_period = 7
# preferred_backup_window = "07:00-09:00"
# preferred_maintenance_window = "sun:04:00-sun:07:00"